### ISSUE TITLE
Mandatory or optional fields

### ISSUE THREAD

**Issue by pritikin** [anima-wg/voucher#3]
There is some inconsistencies in the existing text that need to be resolved (see below). Additionally if a "voucher" can also be a "voucher request" then the requester can't necessarily populate all the fields. These related issues need to be dealt with.    

   leaf nonce {
         type binary {
           length "8..32";
         }
         must "not(../expires-on)";
         description
           "A value that can be used by a pledge in some bootstrapping
            protocols to enable anti-replay protection.  This node is
            optional because it is not used by all bootstrapping
            protocols.

**Comment by pritikin** [comment]
by my reading this is still an issue for date fields

**Comment by kwatsen** [comment]
I'm unsure what the problem is here?  - what's wrong with the 'nonce' leaf above?

K.

**Comment by pritikin** [comment]
The BRSKI document creates a voucher for the request that contains only created-on, nonce, assertion, and pinned-domain-cert (see top of tree in brski). It then states that "All other fields MAY be omitted in a voucher request." 

I'm worried that this violates the 'mandatory' statements in the yang. I think there may be other cases were we state that fields may/maynot exist that again isn't consistent with the formal yang. i might be overly worrying. dunno.

**Comment by pritikin** [comment]
I don't know what is the better approach: (1) all yang fields are optional? or (2) the voucher requests have stubbed out fields to exactly conform to the yang mandatory specifications.

**Comment by pritikin** [comment]
Here is an example of the yang being internally inconsistent. 
my position: make this optional because a pledge doesn't have the time and thus can't populate this field correctly. 

     leaf created-on {
        type yang:date-and-time;
        **mandatory true;**
        description
          "A value indicating the date this voucher was created.  **This
           node is optional** because its primary purpose is for human
           consumption.  However, when present, pledges that have
           reliable clocks SHOULD ensure that this created-on value
           is not greater than the current time.";
      }

**Comment by pritikin** [comment]
Here the BRSKI document doesn't include the serial number from the pledge. The reason why is that the Registrar determines the serial number from the IDevID. There is potential value in a "claimed" serial-number that is not authenticated, maybe. But I don't like the idea of the Registrar being forced to make a decision if the serial-number is different than what the IDevID implies. Again I'd vote this be an optional field. 

      leaf serial-number {
        type string;
        mandatory true;
        description
          "The serial number of the hardware.  When processing a
           voucher, a pledge MUST ensure that its serial number
           matches this value.  If no match occurs, then the
           pledge MUST NOT process this voucher.";
      }

**Comment by kwatsen** [comment]
It's exactly because of stuff like this that I wanted to keep the request format a distinct separate thing.  My opinion is that you have the pledge fill-in dummy values.  

The 'created-on' is suppose to be set by the MASA.  Whether the pledge can make sense of it is not important.  What's important is that inspected by intermediates.   In this sense, it makes sense for it to be mandatory true.

I don't want to water-down what a voucher should be.   I prefer letting the pledges fill-in dummy values, or us defining an explicit request format.

**Comment by toerless** [comment]
1. When Kent was not present, i voiced the opinion to max that logically all fields could be optional because the sender knows what the receiver needs. But i can see Kents point which i think is to keep the model semantically "strong". If we make everything optional and do not even define whether something is a request or an actual voucher, and what element is optional where, then all verification has to be based on context including where on a wire the object is seen, and implementations can much easier make mistakes. That would not be good.

2. Given how the idea of the voucher-request came in fairly late in the process and we are in last call, i think we should concede that we may not be able to resolve all voucher-request related issues without causing unnecessary delay to the voucher document. I would suggest we

2.a) keep the text suggestion that voucher "could" be used for voucher-request (just one sentence). Even if (see below) we may not use solely the voucher.
2.b) Make sure that mandatory definitions and descriptive text is correct for vouchers (not voucher requests).
2.c) If we have any descriptive text in the yang model that was added specifically for the voucher request, we should explicitly say so , else its confusing.

3. I have no problems creating a derived voucher format in the BRSKI document that adds a voucher-request container as an alternative to the voucher container if we see that the MUST statements in the voucher document would make workarounds ("fill in with fake values") would look too gross to us. 

The BRSKI voucher-artifact would then be an extended version of the voucher-artifact and be fully backward compatibe: exactly the same for vouchers, just adding voucher-requests. The only non-ideal thing resulting out of this is that we would have to duplicate all the voucher elements into a voucher-request container (to change MUST/optional). But at least we do not need to duplicaet the voucher container (grouping takes care of that). But i would be very happy: It is syntactically strong and explicit, and i can also complain about YANG being a lame language that doesn't allow me to do this easier than through duplication ;-)

4. If all the above makes sense, i am not quite sure if any of Max'es concerns till need to be resolved, because they look primarily like issues for requests.
