### ISSUE TITLE
Use grouping mechanism to allow for extensibility

### ISSUE THREAD

**Issue by pritikin** [anima-wg/voucher#8]
As part of closing this comment we need to understand how relying parties would handle extensions. We (our anima group) don't fully understand this.

**Comment by pritikin** [comment]
BRSKI won't be needing this extension given the now existing 'prior signed voucher' field. But if there are normative changes needed in order for future extension we need to make these now. We agreed to do this in todays call but i'm unclear exactly what the change looks like. This is our notes: 

voucher doc uses "grouping" 
then when defining a voucher  [future work] can "augment" to add fields.

This might be useful for BRSKI extensions we are currently discussion
Another example use might be network endpoint assessment or other extension.

**Comment by toerless** [comment]
After an earfull of YANG from colleagues and reading rfc8040:

YANG grouping defines just a template. If you want to use it in any place you need to instantiate it first. Its meant for reuse. Grouping are great if you want to reuse definitions. Consider a yang object you need in the config store and in the operations store, you simply instantiate the grouping twice.

Augmentation is another specific YANG construct, but it is only meant to extend an already defined instance in a YANG tree. like some 'bis' version of a module. If you want a derived variant of some tree it's better to first define a grouping and then instantiate the grouping twice with for example extension in the second grouping.

In he current voucher doc (Jun 27 - https://github.com/anima-wg/voucher/blob/7480341bf01fda153a80ea55b49811914e8315bc/draft-ietf-anima-voucher.txt), the word grouping is IMHO just a mistake leftover:

rc:yang-data voucher-artifact {
...
} // end voucher-grouping

voucher-artifact is not a grouping but a YANG data template. Which means that the whole blob inside of it is not a YANG grouping (yang template) or a YANG data instance for any tree, but it is free floating structured message definition in YANG that you can use in any protocol. Aka: just what we need for Netconf and BRSKI.

BUT: Because we use actually in Netconf and in BRSKI the voucher-artifact, we should be careful in BRSKI to also refer to the term "voucher artifact" and not just the "voucher". 

For example. Consider an extension to the voucher artifact adding data that is not logically part of the voucher itself but that makes a lot of sense to be part of the voucher artifact (signed voucher blob):

rc:yang-data voucher-artifact {
    container voucher {
    }
   leaf owner-bootstrap-server {
       // ... string etc to carry a URL indicate method (netconf, BRSKI,...) and server name
   }
} // end of RFC8040 voucher YANG Data scheme

Aka if you got a voucher on a USB stick you wouldn't need to have a separate signed file pointing you to your bootstrap server (registrar/zero-touch-netconf-server), but it could be co-signed into the voucher-artifact object - but clearly not necessarily part of the "voucher" itself.

Just an example. With MASA  online we have other ways to signal the owner-bootstrap-server, BUT:

It would be great if we could make the voucher-artifact extensible so that for example we could later on write an extended voucher-artefact draft that for example adds this bootstrap server.

To that extend, i don't think that the rc:yang-data YANG data schema definition is sufficient to make it easy to build such an extension.

I do not know if the following is the right way to do it, but 

rc:yang-data voucher-artifact {
    uses voucher-artifact-grouping ;
} // instantiating the YANG DATA scheme 

grouping voucher-artifact-grouping {
    container voucher {
        // contains all content of voucher
    }
}

And then in a voucher-artefact extension document one could say:

module ietf-voucher-extended {
    import ietf-voucher {
        prefix "v";
    }

  rc:yang-data voucher-artifact {
      uses voucher-artifact-grouping
  }

 grouping voucher-artifact-grouping {
       uses v:voucher-artifact-grouping;
       leaf owner-bootstrap-server {
           // ... string etc to carry a URL indicate method (netconf, BRSKI,...) and server name
       }
    }
}

Aka: in the extension too we would define the new stuff via a grouping so yet another extension could refer to it easily. 

Of course i am only guessing what the best way is to make it extensible. I specifically don't know if i can use a grouping in another grouping for example... ;-))
